### ISSUE TITLE
Branch develop is for a previous version of Radarr, set branch to 'Aphrodite' for further updates

### ISSUE THREAD

**Issue by znedw** [hotio/docker-radarr#2]
Same as https://github.com/linuxserver/docker-radarr/issues/89

**Comment by smashingtags** [comment]
Just installed can confirm

**Comment by hotio** [comment]
This has nothing to do with docker, it's mereley a health warning from radarr to fix your radarr settings.

**Comment by hotio** [comment]
Fyi, it's just to get the proper changelog in the updates tab, it has nothing to do with actually getting docker updates or whatever...

**Comment by znedw** [comment]
Can you create an app/config.xml with the <Branch> set to whatever the image is or is that too much work / too fragile?

**Comment by TRaSH-** [comment]
In my opinion.
People who use a pre alpha version of Radarr should know the settings of Radarr and what they do.
And if using Dockers how the update works.

**Comment by hotio** [comment]
A 1000x what Trash said.
