### ISSUE TITLE
Update mono for TLS 1.2 support

### ISSUE THREAD

**Issue by RichieB2B** [hotio/docker-radarr#3]
Some indexers have started to require TLS 1.2 or 1.3. Mono 5.20.1.34 does not seem to support this. Please update mono in your docker images.

See also https://github.com/linuxserver/docker-radarr/issues/77

**Comment by hotio** [comment]
I'm able to connect to tls1.2 just fine...

**Comment by RichieB2B** [comment]
Yes, tcpdump shows it is working fine. Sorry for the false alarm.
